# yaml(*.yml)
#     yet another markup language
#     가벼운 마크업 언어로 사용
#
# 기본 문법
#   # 는 주석
#   기본표현
#      key: value     <- : 다음에는 반드시 공백문자가 와야 함
#
#   key:
#       key_1:
#           key_2:
#               key_3:
#                   ..


# 서버포트번호
server:
  port: 8080

spring:
  application:
    name: Bt62_JPA_Board

  # Thymeleaf 설정
  thymeleaf:
    cache: false
    prefix: classpath:templates/views/

  # datasource 설정
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db326?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: user326
    password: 1234

  # security 설정
  security:
    #    user:
    #      name: user
    #      password: 1234
    # oauth2 client
    oauth2:
      client:
        registration:
          google:
            client-id: 1062897662734-db54njeioqhol9nte7ckj1ros34akkh8.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile

          facebook:
            client-id: 1208804653811097
            client-secret: 36416587d0ff062e744610a92868acfb
            scope: #접근권한
              - email
              - public_profile

          naver:
            client-id: 8xDffjo6EgjyGPERRXGA
            client-secret: szAqxCB6Tq
            scope:
              - name
              - email
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/naver

        #provider 제공
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

  #JPA 설정
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

    hibernate:
      # DDL(create, alter, drop) 정의시 DB의 고유 기능을 사용할 수 있다.
      # create: 서버 가동할때마다 기존 테이블을 삭제하고 새로 생성
      # update: DB테이블와 엔티티 매핑정보를 비교해서 변경사항이 있는 경우만 수정 (ALTER). 테이블 없으면 CREATE
      # create-drop: 기본적으로 create 와 동일한 동작을 하나, 종료시점에서 drop
      # none : production 환경으로 배포할때는 반드시 none 으로 하자.
      ddl-auto: create



app:
  #페이징 관련 세팅값
  pagination:
    write_pages: 10 #한 [페이징]당 몇개의 페이지를 표시?
    page_rows: 10 #한 '페이지에 몇개의 글을 리스트할지

  #파일 업로드 경로
  upload:
    path: upload

  #OAuth2
  oauth2:

    password: 1234 #oauth2 인증

    #Kakao로그인
    kakao:
      client-id: 580eb849cebe5470a28a96b26fca76f7 #REST API 앱 키
      redirect-uri: http://localhost:8080/oauth2/kakao/callback #Redirect
      token-uri: https://kauth.kakao.com/oauth/token #access token 요청 uri
      user-info-uri: https://kapi.kakao.com/v2/user/me  # 사용자 profile 요청 URI



